### ISSUE TITLE
Undo behavior

### ISSUE THREAD

**Issue by Zlitus** [luisfontes19/vscode-swissknife#3]
Hello,

I use Swissknife a lot to convert timestamps to dates and dates to timestamps, it is great; especially great with multiple cursor 👍.

However, if I select 50 different timestamp on 50 different cursors and convert them to dates, then I see than I made a mistake on my selection and I want to undo this operation, I will have to undo 50 times!! 1 time for each conversion.

Would it be possible to change this behavior to be able to undo the whole batch at once?

Thank you!!

**Comment by luisfontes19** [comment]
@Zlitus expect the fix in the next version. The code fix has been pushed, but the version might take some more time.

Thank you for the feedback

**Comment by Zlitus** [comment]
Thank you very much, that's amazing. Any idea when the next release will be published? :-)

I also noticed a performance "issue": To convert 700 unix timestamp to date, it took over 9 seconds 😱😅, is this a "normal behavior" in the VSCode & SwissKnife architecture?

https://user-images.githubusercontent.com/5795443/157080639-2de66a85-fa8b-4211-9764-0ae7ad253427.mov

**Comment by luisfontes19** [comment]
hahahaha cool one 😂 Well, that seems to be fixed with the fix for the undo. 
The way I was doing it before i was requesting vscode the TextEditorEdit instance for each cursor and that seems to be the performance bottleneck. Now looks much faster. 

I'm planning to release the update in the next days/week. I want to test it a bit more as I changed the core code that its used basically everywhere in the extension

Also, thank you for showing me that now is possible to do multicursor from selected lines. That was a feature I missed a lot from sublime text (i was doing multi cursor one line at a time)

**Comment by luisfontes19** [comment]
Also, I just added a github action to build the extension package, so if you want to install the extension without waiting for the release to come out you can find the latest builds in the [workflow runs](https://github.com/luisfontes19/vscode-swissknife/actions/workflows/build_artifact.yml) 

[Direct link](https://github.com/luisfontes19/vscode-swissknife/suites/5566133136/artifacts/179875104)

**Comment by luisfontes19** [comment]
1.4.0 released. Let me know if you still have any issue 

Thanks for the feedback
